version: '3.8'
services:
  api:
    image: alixsanta/api_gnhd
    environment:
      DB_URL: postgres://postgres:Nemesis@db:5432/GNHD
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Nemesis
      POSTGRES_USER: postgres
      POSTGRES_DB: GNHD
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  db_data: